AWSTemplateFormatVersion: '2010-09-09'
Description: AWSCodePipelineDeployApiGatewaySpringBoot backend with Docker deployment to EC2 (Admin IAM, No S3)

Parameters:
  GitHubOwner:
    Type: String
    Default: NUS-ISS-SUS-Team2
    Description: NUS-ISS-SUS-Team2
  GitHubRepo:
    Type: String
    Default: securidine-backend
    Description: securidine-backend
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch to track
  ECRRepositoryName:
    Type: String
    Default: nus-iss-sus-team2/securidine
    Description: Name of the Amazon ECR repository [nus-iss-sus-team2/securidine]
  InstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: "t2.micro"
  SSLCertificateArn:
    Type: String
    Default: "arn:aws:acm:ap-southeast-1:302125150179:certificate/a4de7299-0b11-4859-8bea-32f2a72ece6a"
    Description: "Copy the ARN of the existing ACM certificate for HTTPS (use subdomain cert)"
  HostedZoneId:
    Type: String
    Default: "Z01998683DGB4NDJAP1XC"
    Description: Hosted Zone Id
  APIDomainName:
    Type: String
    Default: "api.nusiss-sus-project.online"
    Description: "API domain name for API Gateway (Need to match with wildcard domain registered for cert for HTTPS)" 
  ALBDomainName:
    Type: String
    Default: "alb.nusiss-sus-project.online"
    Description: "ALB domain name for ALB HTTPS (Need to match with wildcard domain registered for cert for HTTPS)"
  KeyName:
    Description: "EC2 KeyPair for SSH access"
    Type: AWS::EC2::KeyPair::KeyName
  VPC:
    Description: "VPC ID where the instance will be deployed"
    Type: AWS::EC2::VPC::Id
  Subnet:
    Description: "Subnet ID for EC2 instance"
    Type: AWS::EC2::Subnet::Id
  SubnetALB:
    Description: "Second Subnet IDs for ALB (Requires more than one - Choose a different one)"
    Type: AWS::EC2::Subnet::Id
  SonarCloudOrganization:
    Type: String
    Default: "nus-iss-sus-team2"
  SonarCloudProjectKey:
    Type: String
    Default: "NUS-ISS-SUS-Team2_securidine-backend"
  SonarCloudToken:
    NoEcho: true
    Type: String
    Default: "85600fd8d7f394aa0e6f1188b832be4b34fba240"
  AWSDefaultRegion:
    Type: String
    Default: "ap-southeast-1"


Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepositoryName

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: securidines3bucket
      VersioningConfiguration:
        Status: Enabled

  APIGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/api-gateway/${AWS::StackName}"
      RetentionInDays: 1

  EC2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/ec2/logs"
      RetentionInDays: 1

  ALBLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/alb/logs"
      RetentionInDays: 1

  CodeDeployLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/codedeploy/logs"
      RetentionInDays: 1

  CodePipelineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/codepipeline/logs"
      RetentionInDays: 1

  OrderServiceWAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "aws-waf-logs-OrderService"
      RetentionInDays: 1

  OrderServiceEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: "ami-0995922d49dc9a17d"  # Replace with latest Amazon Linux 2 AMI ID
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref Subnet
          GroupSet:
            - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: "Order Microservice"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          exec > /var/log/user-data.log 2>&1

          echo "Updating packages..."
          yum update -y

          echo "Installing dependencies..."
          yum install -y docker
          yum install -y ruby wget


          echo "Starting and enabling Docker..."
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ec2-user

          echo "Installing AWS CodeDeploy agent..."
          cd /home/ec2-user
          wget https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto

          echo "Enabling and starting CodeDeploy agent..."
          systemctl enable codedeploy-agent
          systemctl start codedeploy-agent

          echo "Verifying Docker and CodeDeploy installations..."
          docker --version || exit 1
          systemctl status codedeploy-agent || exit 1
          
          echo "Installation for Mysql..."
          dnf update -y
          dnf install -y mariadb105
          
          echo "User Data script completed."

  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow inbound access"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # Allows HTTPS access from anywhere

  EC2InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: AdminAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref EC2InstanceRole
        
  OrderServiceALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "OrderServiceALB"
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref Subnet 
        - !Ref SubnetALB
      SecurityGroups:
        - !Ref EC2SecurityGroup

  OrderServiceALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref OrderServiceALB
      Protocol: HTTPS
      Port: 443
      Certificates:
        - CertificateArn: !Ref SSLCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref OrderServiceTargetGroup

  OrderServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 8080
      Protocol: HTTP
      TargetType: instance
      Targets:
        - Id: !Ref OrderServiceEC2Instance
        
  OrderServiceApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "OrderServiceAPI"
      Description: "API for Order Service"
      Policy:
        Statement:
          - Action: "execute-api:Invoke"
            Effect: "Allow"
            Principal: "*"
            Resource: "arn:aws:execute-api:*"

 
  OrderServiceApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref APIDomainName
      RegionalCertificateArn: !Ref SSLCertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL

  OrderServiceApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref OrderServiceApiDomainName
      RestApiId: !Ref OrderServiceApi

  OrderResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OrderServiceApi
      ParentId: !GetAtt OrderServiceApi.RootResourceId
      PathPart: "order"

  GetAllOrdersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OrderServiceApi
      ParentId: !Ref OrderResource
      PathPart: "getAllOrders"

  GetOrdersMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderServiceApi
      ResourceId: !Ref GetAllOrdersResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: HTTP
        IntegrationHttpMethod: GET
        Uri: !Join ["", ["https://", !Ref ALBDomainName, "/order/getAllOrders"]]
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET, POST, OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'"
            method.response.header.Access-Control-Allow-Methods: "'GET, POST, OPTIONS'"
            method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
            
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - GetOrdersMethod
    Properties:
      RestApiId: !Ref OrderServiceApi
      
  ApiGatewayDeploymentStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref OrderServiceApi
      DeploymentId: !Ref ApiDeployment
      AccessLogSetting:
        DestinationArn: !GetAtt APIGatewayLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength"}'
      StageName: prod
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
        
        
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AdminAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AdminAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: SpringBootDockerBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubOwner}/${GitHubRepo}.git"
        BuildSpec: Order-Service/buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:4.0"
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWSDefaultRegion
          - Name: REPOSITORY_URI
            Value: !Sub "${ECRRepository.RepositoryUri}"
          - Name: JAVA_HOME
            Value: "/usr/lib/jvm/java-17-openjdk"
          - Name: SONAR_TOKEN
            Value: !Ref SonarCloudToken
          - Name: SONAR_ORG
            Value: !Ref SonarCloudOrganization
          - Name: SONAR_PROJECT_KEY
            Value: !Ref SonarCloudProjectKey
      Artifacts:
        Type: NO_ARTIFACTS
      TimeoutInMinutes: 15

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: SpringBootDockerPipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Sub "{{resolve:secretsmanager:GitHubTokenBZ:SecretString:GitHubOAuthToken}}"
                PollForSourceChanges: false  
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: BuildDockerWithSonar
          Actions:
            - Name: BuildDockerAndScan
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject
              OutputArtifacts:
                - Name: BuildOutput

        - Name: Deploy
          Actions:
            - Name: DeployToEC2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              Configuration:
                ApplicationName: SpringBootApp
                DeploymentGroupName: SpringBootDeploymentGroup
              InputArtifacts:
                - Name: BuildOutput
                
        - Name: SecurityScan
          Actions:
            - Name: RunOWASPZAP
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              OutputArtifacts:
                - Name: OWASPZAPReport
              Configuration:
                ProjectName: !Ref CodeBuildSecurityScan
              RunOrder: 1

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: SpringBootApp

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: SpringBootDeploymentGroup
      ServiceRoleArn: !GetAtt CodePipelineRole.Arn
      Ec2TagFilters:
        - Key: Name
          Value: Order Microservice
          Type: KEY_AND_VALUE
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          
  CodeBuildSecurityScan:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: SecurityScan
      Source:
        Type: CODEPIPELINE
        BuildSpec: Order-Service/buildspec-security.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:4.0"
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: API_URL
            Value: !Sub "https://${OrderServiceApi}.execute-api.${AWS::Region}.amazonaws.com/prod/order/getAllOrders"
          - Name: REPORT_BUCKET
            Value: !Ref ArtifactBucket
      ServiceRole: !GetAtt CodePipelineRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  OrderServiceWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: OrderServiceWebACL
      Scope: REGIONAL
      DefaultAction:
        Allow: {}  # allow traffic here
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: OrderServiceWebACL
      Rules: [] # filter rules here


  OrderServiceWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn: 
      - OrderServiceWebACL
      - OrderServiceApi
      - ApiGatewayDeploymentStage 
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${OrderServiceApi}/stages/prod"
      WebACLArn: !GetAtt OrderServiceWebACL.Arn

  OrderServiceWAFLogging:
    Type: AWS::WAFv2::LoggingConfiguration
    DependsOn: 
      - OrderServiceWAFLogGroup
      - OrderServiceWebACL
    Properties:
      LogDestinationConfigs:
        - !GetAtt OrderServiceWAFLogGroup.Arn
      ResourceArn: !GetAtt OrderServiceWebACL.Arn


  CloudWatchLogRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudWatchLoggingRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - apigateway.amazonaws.com
                - codedeploy.amazonaws.com
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
     
  APIGatewayDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId 
      Name: !Ref APIDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt OrderServiceApiDomainName.RegionalDomainName
        HostedZoneId: !GetAtt OrderServiceApiDomainName.RegionalHostedZoneId     
     
  ApiGatewayToALBRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ALBDomainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt OrderServiceALB.CanonicalHostedZoneID
        DNSName: !GetAtt OrderServiceALB.DNSName
      
Outputs:
  PipelineName:
    Description: Name of the AWS CodePipeline
    Value: !Ref CodePipeline
